version: "3.9"

services:
  redis:
    image: redis:6-alpine
    networks:
      - walletconnect-monorepo
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
  caddy:
    image: caddy
    volumes:
      - ../Caddyfile:/Caddyfile
    command: caddy run -config /Caddyfile
    ports:
      - 80:80
      - 443:443
  relay:
    deploy:
      replicas: 2
    networks:
      - walletconnect-monorepo
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RELAY_MODE=any
    volumes:
      - node_modules:/usr/src/app/node_modules
      - ../../servers/relay/src:/usr/src/app/src
        #healthcheck:
        #test: ["CMD", "wget", "-qO-", "http://localhost:5000/health"]
        #interval: 5s
        #timeout: 5s
        #retries: 5
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis:
  waku-store:
  waku:
  node_modules:

networks:
  walletconnect-monorepo:
    driver: bridge
